routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('reservas', 'ReservasController')->middleware('verified');

app/Reserva.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reserva extends Model
{
    protected $fillable = ['start', 'end', 'user_id'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/ReservasController.php
<?php

namespace App\Http\Controllers;

use App\Reserva;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ReservasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reservas = Reserva::get();

        $lim = sizeof($reservas);
        for ($i=0; $i < $lim; $i++) { 
            $reservas[$i]['user_id'] = User::find($reservas[$i]['user_id'])->name;
        }

        return view('reservas.index', compact('reservas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('reservas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'date' => 'required|date',
            'start' => 'required',
            'end' => 'required',
        ]);

        // TODO: comprobar start y end (max dos horas)
        // TODO: comprobar que el usuario no tiene reservas ya para ese dia (solo una por dia)
        // TODO: comprobar que no hay reservas de otro usuario en ese tramo (solo tenemos una pista, no pueden jugar dos a la vez)
        // TODO: comprobar que la reserva no es de mas de una semana en el futuro
        // TODO: comprobar que la reserva no se hace en el pasado

        // creo que este if puede ser util para comprobar esas cosas:
        // if ($reserva['user_id'] != Auth::id()) {
        //     $status = "error";
        //     $message = "No se puede editar la reserva de otro usuario";
        //     return redirect('/reservas')->with($status, $message);
        // }

        $date = $request->get('date');
        $start = $date . " " . $request->get('start');
        $end = $date . " " . $request->get('end');

        $reserva = new Reserva([
            'start' => $start,
            'end' => $end,
            'user_id' => Auth::id(),
        ]);
        $reserva->save();

        $status = "success";
        $message = "La reserva " . $reserva . " se ha anadido";

        return redirect('/reservas')->with($status, $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $reserva = Reserva::findOrFail($id);

        if ($reserva['user_id'] != Auth::id()) {
            $status = "error";
            $message = "No se puede editar la reserva de otro usuario";
            return redirect('/reservas')->with($status, $message);
        }

        return view('reservas.edit', compact('reserva'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // TODO: aqui hay que validarlo todo tambien
        $request->validate([
            'start' => 'required|date',
            'end' => 'required|date',
        ]);

        $reserva = Reserva::findOrFail($id);
        $reserva->start = $request->get('start');
        $reserva->end = $request->get('end');
        $reserva->save();

        $status = "success";
        $message = "La reserva " . $reserva . " se ha actualizado";
        return redirect('/reservas')->with($status, $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $reserva = Reserva::find($id);

        if ($reserva['user_id'] != Auth::id()) {
            $status = "error";
            $message = "No se puede borrar la reserva de otro usuario";
            return redirect('/reservas')->with($status, $message);
        }

        $reserva->delete();
        $status = "success";
        $message = "La reserva " . $reserva . " se ha borrado";
        return redirect('/reservas')->with($status, $message);
    }
}

resources/views/reservas/create.blade.php
@extends('layouts.app')

@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
<div class="container">
    <div class="card uper">
        <div class="card-header">
            Add Site
        </div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif
            <!-- TODO: cambiar formato por un selector de horas entre las disponibles y limitar a max 2 horas -->
            <form method="post" action="{{ route('reservas.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="start">Reservar el dia:</label>
                    <input type="date" class="form-control" name="date"/>
                </div>
                <div class="form-group">
                    <label for="end">Desde las:</label>
                    <input type="time" class="form-control" name="start"/>
                </div>
                <div class="form-group">
                    <label for="end">Hasta las:</label>
                    <input type="time" class="form-control" name="end"/>
                </div>
                <button type="submit" class="btn btn-primary">Reservar</button>
                <a class="btn btn-secondary" href="{{ route('reservas.index') }}"> Cancel</a>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/reservas/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="container">
  <div class="card uper">
    <div class="card-header">
      Editar Reserva
    </div>
    <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div><br />
      @endif
      <form method="post" action="{{ route('reservas.update', $reserva->id) }}">
        @method('PUT')
        @csrf
        <div class="form-group">
          <label for="start">Desde:</label>
          <input type="text" class="form-control" name="start" value={{ $reserva->start }} />
          <!-- TODO: castear la mierda que llega a lo mismo que el create (hacer primero create) -->
        </div>
        <div class="form-group">
          <label for="end">Hasta:</label>
          <input type="text" class="form-control" name="end" value={{ $reserva->end }} />
        </div>
        <button type="submit" class="btn btn-primary">Actualizar</button>
        <a class="btn btn-secondary" href="{{ route('reservas.index') }}"> Cancel</a>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/reservas/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div class="container">
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="row">

        <div class="pull-left col-8">
          <h2>Listado de reservas de la pista de padel</h2>
        </div>
        <div class="pull-right col-4" align="right">
          <a class="btn btn-success mr-4 mb-2" href="{{ route('reservas.create') }}"> Reservar pista</a>
        </div>
      </div>
    </div>
  </div>

  <div class="uper">
    @if (session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
    @endif
    @if (session()->get('error'))
    <div class="alert alert-danger">
      {{ session()->get('error') }}
    </div><br />
    @endif

    <table class="table table-striped">
      <thead>
        <tr>
          <td>ID</td>
          <td>Desde</td>
          <td>Hasta</td>
          <td>Usuario</td>
          <td colspan="2">Action</td>
        </tr>
      </thead>
      <tbody>
        @foreach($reservas as $reserva)
        <tr>
          <td>{{$reserva->id}}</td>
          <td>{{$reserva->start}}</td>
          <td>{{$reserva->end}}</td>
          <td>{{$reserva->user_id}}</td>
          <td><a href="{{ route('reservas.edit',$reserva->id)}}" class="btn btn-primary">Editar</a></td>
          <td>
            <form action="{{ route('reservas.destroy', $reserva->id)}}" method="post">
              @csrf
              @method('DELETE')
              <button class="btn btn-danger" type="submit">Borrar</button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    <div>
    </div>
    @endsection